# Generated by Django 5.2.4 on 2025-07-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipoconsulta', models.IntegerField(choices=[(0, 'Consulta'), (1, 'Sugerencia'), (2, 'Reclamo'), (3, 'Petición'), (4, 'Queja'), (5, 'Felicitación'), (6, 'Otro')], default=0)),
                ('mensaje', models.TextField()),
                ('avisos', models.BooleanField(default=False)),
            ],
        ),
    ]
