# Generated by Django 5.2.4 on 2025-08-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obituario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_fallecimiento', models.DateField()),
                ('mensaje', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='obituarios/')),
            ],
        ),
    ]
