# Generated by Django 5.2.4 on 2025-08-06 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0002_obituario'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleObituario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_exequias', models.CharField(blank=True, max_length=100)),
                ('fecha_exequias', models.DateTimeField(blank=True, null=True)),
                ('hora_exequias', models.TimeField(blank=True, null=True)),
                ('lugar_velatorio', models.CharField(blank=True, max_length=100)),
                ('destino_final', models.CharField(blank=True, max_length=100)),
                ('invitaciones', models.TextField(blank=True, null=True)),
                ('obituario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_gestion.obituario')),
            ],
        ),
    ]
