# Generated by Django 5.2.4 on 2025-08-06 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0003_detalleobituario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleobituario',
            name='hora_exequias',
        ),
    ]
