# Generated by Django 5.2.4 on 2025-08-13 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0004_remove_detalleobituario_hora_exequias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condolencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_remitente', models.CharField(max_length=100)),
                ('email_remitente', models.EmailField(max_length=254)),
                ('telefono_remitente', models.CharField(blank=True, max_length=15, null=True)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('obituario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condolencias', to='app_gestion.obituario')),
            ],
        ),
    ]
